os: Visual Studio 2015

platform:
  - x64

configuration: Test

skip_tags: true

build: off

environment:
  nodejs_version: "8.9.0"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force

test_script:
  - yarn run lint
  - yarn run test

for:
  - branches:
      only:
        - /^release\/v.*/
    configuration: Release
    test_script:
      - yarn run lint
      - yarn run test
      - yarn run publish
