os: osx
osx_image: xcode9.2

language: node_js
node_js:
  - "8.9.0"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

cache:
  yarn: true
  timeout: 600
  directories:
    - $HOME/.electron

script:
  - yarn run lint
  - yarn run test
  - if [[ $TRAVIS_BRANCH =~ release/.+ ]]; then yarn run publish; fi
