os: osx
osx_image: xcode9.2

language: node_js
node_js:
  - "8.9.0"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

cache:
  yarn: true
  timeout: 600
  directories:
    - "node_modules"
    - $HOME/.electron
    - $HOME/Library/Caches/Yarn/v1
    - $HOME/Library/Caches/electron-builder

install:
  - npm install -g yarn
  - yarn install --force

script:
  - yarn run lint
  - yarn run test

deploy:
  provider: script
  script: yarn run publish
  on:
    branch: /^release\/v.*/