os:
  - osx
  - linux
  - windows

language: node_js
node_js:
  - "8.9.0"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run make test; fi
  - yarn run lint
  - yarn run test
  - if [[ $TRAVIS_BRANCH =~ release/.+ ]]; then yarn run publish; fi
