os: Visual Studio 2015

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

branches:
  only:
    - master

skip_tags: true

install:
  - ps: Install-Product node LTS
  - yarn install --force

build: off

test_script:
  - yarn ci
