os: Visual Studio 2015

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node LTS
  - yarn install --force

build: off

test_script:
  - yarn run lint
  - yarn run test

on_success:
  - IF %APPVEYOR_REPO_BRANCH%==master yarn run dist