version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.9.4-browsers
    steps:
      - checkout
      - run: yarn install --force
      - run: yarn run lint
      - run: yarn run test