appId: com.example.electron-starter

directories:
  output: dist
  app: tmp/prod/app

publish:
  provider: github
  owner: hokaccha
  repo: electron-starter

win:
  target:
    - nsis

mac:
  target:
    - zip
    - dmg
  category: public.app-category.developer-tools

linux:
  target:
    - AppImage
    - deb
    - rpm
  category: Utility
